# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c573d346e7a00d98033200b2c145fc0c245cb0626b8633f4a7237a0b2a91473f57e0ebd02e38a9d3d907d9cf13c02833350faa9b217840599dc2b1144c609a54

test:
  secret_key_base: 4795cffe13f41c9b37b60bd575ac202cdeefd0b5c517f56b9d9f1f7ca3e4dc13a2e51a07935df709e0523af2e7dab354d95373c5584e28cc37803b66af87b4fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
